# https://docs.frigate.video/installation
version: "3.9"
services:
  tre-data-usage:
    build: .
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      - TZ=Europe/Stockholm
